[[domains]]
tld = "ac.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "co.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "gov.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "mil.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "net.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "org.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"

[[domains]]
tld = "sch.ae"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ae.html"
