[[domains]]
tld = "accident-investigation.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "accident-prevention.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "aerobatic.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "aeroclub.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "aerodrome.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "agents.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "air-surveillance.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "air-traffic-control.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "aircraft.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "airline.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "airport.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "airtraffic.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "ambulance.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "association.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "author.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "ballooning.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "broker.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "caa.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "cargo.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "catering.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "certification.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "championship.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "charter.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "civilaviation.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "club.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "conference.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "consultant.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "consulting.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "control.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "council.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "crew.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "design.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "dgca.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "educator.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "emergency.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "engine.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "engineer.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "entertainment.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "equipment.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "exchange.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "express.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "federation.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "flight.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "freight.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "fuel.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "gliding.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "government.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "groundhandling.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "group.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "hanggliding.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "homebuilt.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "insurance.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "journal.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "journalist.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "leasing.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "logistics.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "magazine.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "maintenance.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "marketplace.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "media.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "microlight.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "modelling.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "navigation.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "parachuting.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "paragliding.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "passenger-association.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "pilot.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "press.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "production.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "recreation.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "repbody.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "res.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "research.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "rotorcraft.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "safety.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "scientist.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "services.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "show.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "skydiving.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "software.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "student.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "taxi.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "trader.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "trading.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "trainer.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "union.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "workinggroup.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"

[[domains]]
tld = "works.aero"
registerable = "yes"
[domains.sources]
registerable = "https://information.aero/registration/policies/dmp"
