[[domains]]
tld = "ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"

[[domains]]
tld = "co.ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"

[[domains]]
tld = "com.ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"

[[domains]]
tld = "net.ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"

[[domains]]
tld = "nom.ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"

[[domains]]
tld = "org.ag"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ag/prices.htm"
