[[domains]]
tld = "al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "com.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "edu.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "gov.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "mil.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "net.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"

[[domains]]
tld = "org.al"
registerable = "yes"
[domains.sources]
registerable = "http://www.ert.gov.al/ert_alb/faq_det.html?Id=31"
