[[domains]]
tld = "am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"

[[domains]]
tld = "co.am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"

[[domains]]
tld = "com.am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"

[[domains]]
tld = "commune.am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"

[[domains]]
tld = "net.am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"

[[domains]]
tld = "org.am"
registerable = "yes"
[domains.sources]
registerable = "https://www.amnic.net/policy/en/Policy_EN.pdf"
