[[domains]]
tld = "arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "e164.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "home.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "in-addr.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "ip6.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "iris.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "uri.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"

[[domains]]
tld = "urn.arpa"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/arpa.html"
