[[domains]]
tld = "ac.at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"

[[domains]]
tld = "at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"

[[domains]]
tld = "co.at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"

[[domains]]
tld = "gv.at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"

[[domains]]
tld = "or.at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"

[[domains]]
tld = "sth.ac.at"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/at.html"
