[[domains]]
tld = "bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "biz.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "co.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "com.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "edu.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "gov.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "info.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "net.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "org.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "store.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"

[[domains]]
tld = "tv.bb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/bb.html"
