[[domains]]
tld = "0.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "1.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "2.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "3.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "4.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "5.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "6.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "7.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "8.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "9.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "a.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "b.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "c.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "d.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "e.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "f.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "g.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "h.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "i.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "j.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "k.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "l.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "m.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "n.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "o.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "p.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "q.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "r.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "s.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "t.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "u.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "v.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "w.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "x.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "y.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"

[[domains]]
tld = "z.bg"
registerable = "yes"
[domains.sources]
registerable = "https://www.register.bg/user/static/rules/en/index.html"
