[[domains]]
tld = "bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"

[[domains]]
tld = "co.bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"

[[domains]]
tld = "com.bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"

[[domains]]
tld = "edu.bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"

[[domains]]
tld = "or.bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"

[[domains]]
tld = "org.bi"
registerable = "yes"
[domains.sources]
registerable = "http://whois.nic.bi/"
