[[domains]]
tld = "africa.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "agro.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "architectes.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "assur.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "avocats.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "co.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "com.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "eco.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "econo.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "edu.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "info.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "loisirs.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "money.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "net.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "org.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "ote.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "restaurant.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "resto.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "tourism.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"

[[domains]]
tld = "univ.bj"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bj/bj-suffixes.txt"
