[[domains]]
tld = "academia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "agro.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "arte.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "blog.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "bolivia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "ciencia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "com.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "cooperativa.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "democracia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "deporte.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "ecologia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "economia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "edu.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "empresa.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "gob.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "indigena.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "industria.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "info.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "int.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "medicina.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "mil.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "movimiento.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "musica.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "natural.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "net.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "nombre.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "noticias.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "org.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "patria.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "plurinacional.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "politica.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "profesional.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "pueblo.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "revista.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "salud.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "tecnologia.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "tksat.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "transporte.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "tv.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "web.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"

[[domains]]
tld = "wiki.bo"
registerable = "yes"
[domains.sources]
registerable = "https://nic.bo"
