[[domains]]
tld = "bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "co.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "com.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "edu.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "gov.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "net.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"

[[domains]]
tld = "org.bz"
registerable = "yes"
[domains.sources]
registerable = "http://www.belizenic.bz/"
