[[domains]]
tld = "ac.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "asso.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "aéroport.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "co.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "com.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "ed.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "edu.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "go.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "gouv.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "int.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "net.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "or.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"

[[domains]]
tld = "org.ci"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ci.html"
