[[domains]]
tld = "cl"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.cl"

[[domains]]
tld = "co.cl"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.cl"

[[domains]]
tld = "gob.cl"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.cl"

[[domains]]
tld = "gov.cl"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.cl"

[[domains]]
tld = "mil.cl"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.cl"
