[[domains]]
tld = "ac.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "ah.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "bj.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "com.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "cq.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "edu.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "fj.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "gd.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "gov.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "gs.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "gx.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "gz.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "ha.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "hb.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "he.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "hi.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "hk.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "hl.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "hn.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "jl.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "js.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "jx.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "ln.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "mil.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "mo.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "net.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "nm.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "nx.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "org.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "qh.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "sc.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "sd.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "sh.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "sn.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "sx.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "tj.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "tw.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "xj.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "xz.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "yn.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "zj.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "公司.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "網絡.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"

[[domains]]
tld = "网络.cn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cn.html"
