[[domains]]
tld = "com.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "edu.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "gob.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "inf.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "nat.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "net.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"

[[domains]]
tld = "org.cu"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cu.html"
