[[domains]]
tld = "cx"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cx.html"

[[domains]]
tld = "gov.cx"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cx.html"
