[[domains]]
tld = "cz"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cz.html"

[[domains]]
tld = "gov.cz"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/cz.html"
