[[domains]]
tld = "art.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "com.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "edu.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "gob.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "gov.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "mil.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "net.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "org.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "sld.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"

[[domains]]
tld = "web.do"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/do.html"
