[[domains]]
tld = "ac.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "com.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "edu.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "eun.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "gov.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "info.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "me.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "mil.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "name.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "net.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "org.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "sci.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "sport.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"

[[domains]]
tld = "tv.eg"
registerable = "yes"
[domains.sources]
registerable = "https://domain.eg/en/domain-rules/subdomain-names-types/"
