[[domains]]
tld = "asso.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "avoues.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "cci.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "com.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "gouv.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "greta.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "huissier-justice.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "nom.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "prd.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"

[[domains]]
tld = "tm.fr"
registerable = "yes"
[domains.sources]
registerable = "https://www.afnic.fr/"
