[[domains]]
tld = "co.gg"
registerable = "yes"
[domains.sources]
registerable = "https://www.channelisles.net/register-1/register-direct"

[[domains]]
tld = "gg"
registerable = "yes"
[domains.sources]
registerable = "https://www.channelisles.net/register-1/register-direct"

[[domains]]
tld = "net.gg"
registerable = "yes"
[domains.sources]
registerable = "https://www.channelisles.net/register-1/register-direct"

[[domains]]
tld = "org.gg"
registerable = "yes"
[domains.sources]
registerable = "https://www.channelisles.net/register-1/register-direct"
