[[domains]]
tld = "com.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "edu.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "gov.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "ltd.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "mod.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"

[[domains]]
tld = "org.gi"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gi/rules.html"
