[[domains]]
tld = "asso.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "com.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "edu.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "mobi.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "net.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"

[[domains]]
tld = "org.gp"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.gp/index.php?lang=en"
