[[domains]]
tld = "com.gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"

[[domains]]
tld = "edu.gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"

[[domains]]
tld = "gov.gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"

[[domains]]
tld = "gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"

[[domains]]
tld = "net.gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"

[[domains]]
tld = "org.gr"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/gr.html"
