[[domains]]
tld = "com.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "edu.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "gob.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "ind.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "mil.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "net.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"

[[domains]]
tld = "org.gt"
registerable = "yes"
[domains.sources]
registerable = "https://www.gt/sitio/registration_policy.php?lang=en"
