[[domains]]
tld = "com.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "edu.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "gob.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "mil.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "net.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"

[[domains]]
tld = "org.hn"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/hn.html"
