[[domains]]
tld = "adult.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "art.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "asso.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "com.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "coop.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "edu.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "firm.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "gouv.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "info.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "med.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "net.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "org.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "perso.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "pol.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "pro.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "rel.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"

[[domains]]
tld = "shop.ht"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ht/info/charte.cfm"
