[[domains]]
tld = "ac.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "biz.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "co.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "desa.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "go.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "kop.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "mil.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "my.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "net.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "or.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "ponpes.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "sch.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "web.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"

[[domains]]
tld = "ᬩᬮᬶ.id"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/id.html"
