[[domains]]
tld = "ass.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "asso.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "com.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "coop.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "edu.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "gouv.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "gov.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "medecin.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "mil.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "nom.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "notaires.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "org.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "pharmaciens.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "prd.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "presse.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"

[[domains]]
tld = "tm.km"
registerable = "yes"
[domains.sources]
registerable = "http://www.domaine.km/documents/charte.doc"

[[domains]]
tld = "veterinaire.km"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/km.html"
