[[domains]]
tld = "edu.kn"
registerable = "yes"
[domains.sources]
registerable = "http://www.dot.kn/domainRules.html"

[[domains]]
tld = "gov.kn"
registerable = "yes"
[domains.sources]
registerable = "http://www.dot.kn/domainRules.html"

[[domains]]
tld = "kn"
registerable = "yes"
[domains.sources]
registerable = "http://www.dot.kn/domainRules.html"

[[domains]]
tld = "net.kn"
registerable = "yes"
[domains.sources]
registerable = "http://www.dot.kn/domainRules.html"

[[domains]]
tld = "org.kn"
registerable = "yes"
[domains.sources]
registerable = "http://www.dot.kn/domainRules.html"
