[[domains]]
tld = "com.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "edu.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "emb.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "gov.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "ind.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "net.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"

[[domains]]
tld = "org.kw"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.kw/policies/"
