[[domains]]
tld = "com.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "edu.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "gov.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "mil.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "net.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"

[[domains]]
tld = "org.kz"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.kz/rules/index.jsp"
