[[domains]]
tld = "com.lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"

[[domains]]
tld = "edu.lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"

[[domains]]
tld = "gov.lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"

[[domains]]
tld = "lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"

[[domains]]
tld = "net.lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"

[[domains]]
tld = "org.lb"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lb.html"
