[[domains]]
tld = "com.lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"

[[domains]]
tld = "edu.lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"

[[domains]]
tld = "gov.lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"

[[domains]]
tld = "lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"

[[domains]]
tld = "net.lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"

[[domains]]
tld = "org.lr"
registerable = "yes"
[domains.sources]
registerable = "http://psg.com/dns/lr/lr.txt"
