[[domains]]
tld = "ac.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "biz.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "co.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "edu.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "gov.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "info.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "net.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "org.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"

[[domains]]
tld = "sc.ls"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ls/"
