[[domains]]
tld = "gov.lt"
registerable = "yes"
[domains.sources]
registerable = "http://www.gov.lt/index_en.php"

[[domains]]
tld = "lt"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lt.html"
