[[domains]]
tld = "asn.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "com.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "conf.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "edu.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "gov.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "id.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "mil.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "net.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"

[[domains]]
tld = "org.lv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/lv.html"
