[[domains]]
tld = "com.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "edu.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "gov.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "id.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "med.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "net.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "org.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "plc.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"

[[domains]]
tld = "sch.ly"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ly/regulations.php"
