[[domains]]
tld = "com.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "edu.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "gov.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "inf.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "name.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "net.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"

[[domains]]
tld = "org.mk"
registerable = "yes"
[domains.sources]
registerable = "http://dns.marnet.net.mk/postapka.php"
