[[domains]]
tld = "ac.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "art.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "asso.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "com.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "edu.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "gouv.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "gov.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "info.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "inst.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "net.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "org.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "pr.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"

[[domains]]
tld = "presse.ml"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ml.html"
