[[domains]]
tld = "com.mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"

[[domains]]
tld = "edu.mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"

[[domains]]
tld = "gov.mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"

[[domains]]
tld = "mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"

[[domains]]
tld = "net.mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"

[[domains]]
tld = "org.mo"
registerable = "yes"
[domains.sources]
registerable = "http://www.monic.net.mo/"
