[[domains]]
tld = "com.ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"

[[domains]]
tld = "edu.ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"

[[domains]]
tld = "gov.ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"

[[domains]]
tld = "ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"

[[domains]]
tld = "net.ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"

[[domains]]
tld = "org.ms"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/ms.html"
