[[domains]]
tld = "aero.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "biz.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "com.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "coop.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "edu.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "gov.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "info.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "int.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "mil.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "museum.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "name.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "net.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "org.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"

[[domains]]
tld = "pro.mv"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/mv.html"
