[[domains]]
tld = "ac.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "biz.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "co.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "com.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "coop.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "edu.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "gov.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "int.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "net.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"

[[domains]]
tld = "org.mw"
registerable = "yes"
[domains.sources]
registerable = "http://www.registrar.mw/"
