[[domains]]
tld = "com.mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"

[[domains]]
tld = "edu.mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"

[[domains]]
tld = "gob.mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"

[[domains]]
tld = "mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"

[[domains]]
tld = "net.mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"

[[domains]]
tld = "org.mx"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.mx/"
