[[domains]]
tld = "biz.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "com.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "edu.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "gov.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "mil.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "name.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "net.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"

[[domains]]
tld = "org.my"
registerable = "yes"
[domains.sources]
registerable = "https://mynic.my/resources/domains/buying-a-domain/"
