[[domains]]
tld = "alt.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "co.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "com.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "gov.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "net.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"

[[domains]]
tld = "org.na"
registerable = "yes"
[domains.sources]
registerable = "http://www.na-nic.com.na/"
