[[domains]]
tld = "asso.nc"
registerable = "yes"
[domains.sources]
registerable = "http://www.cctld.nc/"

[[domains]]
tld = "nc"
registerable = "yes"
[domains.sources]
registerable = "http://www.cctld.nc/"

[[domains]]
tld = "nom.nc"
registerable = "yes"
[domains.sources]
registerable = "http://www.cctld.nc/"
