[[domains]]
tld = "arts.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "com.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "firm.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "info.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "net.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "other.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "per.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "rec.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "store.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"

[[domains]]
tld = "web.nf"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/nf.html"
