[[domains]]
tld = "biz.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "com.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "edu.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "gov.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "info.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "net.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"

[[domains]]
tld = "org.nr"
registerable = "yes"
[domains.sources]
registerable = "http://cenpac.net.nr/dns/index.html"
