[[domains]]
tld = "abo.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "ac.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "com.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "edu.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "gob.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "ing.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "med.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "net.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "nom.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "org.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"

[[domains]]
tld = "sld.pa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.pa/"
