[[domains]]
tld = "com.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "edu.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "gov.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "net.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "org.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "plo.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"

[[domains]]
tld = "sec.ps"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.ps/registration/policy.html#reg"
