[[domains]]
tld = "com.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "edu.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "gov.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "int.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "net.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "nome.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "org.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"

[[domains]]
tld = "publ.pt"
registerable = "yes"
[domains.sources]
registerable = "https://www.dns.pt/en/domain/pt-terms-and-conditions-registration-rules/"
