[[domains]]
tld = "gov.pw"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/pw.html"

[[domains]]
tld = "pw"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/pw.html"
