[[domains]]
tld = "com.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "coop.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "edu.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "gov.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "mil.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "net.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "org.py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"

[[domains]]
tld = "py"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/py.html"
