[[domains]]
tld = "arts.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "com.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "firm.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "info.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "nom.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "nt.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "org.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "rec.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "store.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "tm.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"

[[domains]]
tld = "www.ro"
registerable = "yes"
[domains.sources]
registerable = "http://www.rotld.ro/"
