[[domains]]
tld = "com.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "edu.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "gov.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "med.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "net.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "org.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "pub.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"

[[domains]]
tld = "sch.sa"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.net.sa/"
