[[domains]]
tld = "com.sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"

[[domains]]
tld = "edu.sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"

[[domains]]
tld = "gov.sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"

[[domains]]
tld = "net.sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"

[[domains]]
tld = "org.sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"

[[domains]]
tld = "sc"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.sc/"
