[[domains]]
tld = "a.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "ac.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "b.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "bd.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "brand.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "c.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "d.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "e.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "f.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "fh.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "fhsk.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "fhv.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "g.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "h.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "i.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "k.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "komforb.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "kommunalforbund.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "komvux.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "l.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "lanbib.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "m.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "n.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "naturbruksgymn.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "o.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "org.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "p.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "parti.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "pp.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "press.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "r.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "s.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "t.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "tm.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "u.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "w.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "x.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "y.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"

[[domains]]
tld = "z.se"
registerable = "yes"
[domains.sources]
registerable = "https://data.internetstiftelsen.se/barred_domains_list.txt"
