[[domains]]
tld = "com.sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"

[[domains]]
tld = "edu.sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"

[[domains]]
tld = "gov.sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"

[[domains]]
tld = "net.sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"

[[domains]]
tld = "org.sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"

[[domains]]
tld = "sg"
registerable = "yes"
[domains.sources]
registerable = "https://www.sgnic.sg/domain-registration/sg-categories-rules"
