[[domains]]
tld = "sk"
registerable = "yes"
banned = ["za"]
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sk.html"
banned = "https://www.iana.org/domains/root/db/sk.html"

[[domains]]
tld = "org.sk"
registerable = "yes"
[domains.sources]
registerable = "https://sk-nic.sk/"
