[[domains]]
tld = "com.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "edu.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "gov.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "me.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "net.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "org.so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"

[[domains]]
tld = "so"
registerable = "yes"
[domains.sources]
registerable = "http://sonic.so/policies/"
