[[domains]]
tld = "com.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "edu.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "gov.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "mil.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "net.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "org.sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"

[[domains]]
tld = "sy"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/sy.html"
