[[domains]]
tld = "ac.sz"
registerable = "yes"
[domains.sources]
registerable = "http://www.sispa.org.sz/"

[[domains]]
tld = "co.sz"
registerable = "yes"
[domains.sources]
registerable = "http://www.sispa.org.sz/"

[[domains]]
tld = "org.sz"
registerable = "yes"
[domains.sources]
registerable = "http://www.sispa.org.sz/"

[[domains]]
tld = "sz"
registerable = "yes"
[domains.sources]
registerable = "http://www.sispa.org.sz/"
