[[domains]]
tld = "co.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "com.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "edu.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "gov.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "mil.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "net.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "nom.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "org.tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"

[[domains]]
tld = "tm"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tm/local.html"
