[[domains]]
tld = "com.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "edu.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "gov.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "mil.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "net.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "org.to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"

[[domains]]
tld = "to"
registerable = "yes"
[domains.sources]
registerable = "https://www.iana.org/domains/root/db/to.html"
