[[domains]]
tld = "av.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "bbs.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "bel.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "biz.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "com.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "dr.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "edu.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "gen.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "gov.nc.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "gov.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "info.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "k12.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "kep.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "mil.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "name.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "nc.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "net.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "org.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "pol.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "tel.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "tsk.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "tv.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"

[[domains]]
tld = "web.tr"
registerable = "yes"
[domains.sources]
registerable = "https://nic.tr/index.php?USRACTN=PRICELST"
