[[domains]]
tld = "biz.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "co.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "com.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "edu.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "gov.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "info.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "mil.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "name.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "net.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "org.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "pro.tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"

[[domains]]
tld = "tt"
registerable = "yes"
[domains.sources]
registerable = "https://www.nic.tt/"
