[[domains]]
tld = "club.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "com.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "ebiz.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "edu.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "game.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "gov.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "idv.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "mil.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "net.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "org.tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"

[[domains]]
tld = "tw"
registerable = "yes"
[domains.sources]
registerable = "https://twnic.tw/dnservice_catag.php"
