[[domains]]
tld = "ac.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "co.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "go.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "hotel.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "info.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "me.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "mil.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "mobi.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "ne.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "or.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "sc.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "tv.tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"

[[domains]]
tld = "tz"
registerable = "yes"
[domains.sources]
registerable = "http://www.tznic.or.tz/index.php/domains"
