[[domains]]
tld = "ac.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "co.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "com.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "edu.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "go.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "gov.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "mil.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "ne.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "or.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "org.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "sc.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"

[[domains]]
tld = "us.ug"
registerable = "yes"
[domains.sources]
registerable = "https://www.registry.co.ug"
