[[domains]]
tld = "com.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "edu.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "gub.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "mil.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "net.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "org.uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"

[[domains]]
tld = "uy"
registerable = "yes"
[domains.sources]
registerable = "http://www.nic.org.uy/"
