[[domains]]
tld = "arts.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "bib.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "co.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "com.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "e12.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "edu.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "emprende.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "firm.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "gob.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "gov.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "ia.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "info.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "int.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "mil.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "net.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "nom.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "org.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "rar.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "rec.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "store.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "tec.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"

[[domains]]
tld = "web.ve"
registerable = "yes"
[domains.sources]
registerable = "https://nic.ve/site/user-agreement"
