[[domains]]
tld = "ac.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "ai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "angiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "bacgiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "backan.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "baclieu.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "bacninh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "baria-vungtau.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "bentre.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "binhdinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "binhduong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "binhphuoc.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "binhthuan.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "biz.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "camau.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "cantho.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "caobang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "com.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "daklak.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "daknong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "danang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "dienbien.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "dongnai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "dongthap.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "edu.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "gialai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "gov.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hagiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "haiduong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "haiphong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hanam.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hanoi.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hatinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "haugiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "health.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hoabinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hue.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "hungyen.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "id.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "info.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "int.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "io.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "khanhhoa.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "kiengiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "kontum.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "laichau.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "lamdong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "langson.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "laocai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "longan.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "namdinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "name.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "net.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "nghean.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "ninhbinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "ninhthuan.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "org.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "phutho.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "phuyen.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "pro.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "quangbinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "quangnam.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "quangngai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "quangninh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "quangtri.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "soctrang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "sonla.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "tayninh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "thaibinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "thainguyen.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "thanhhoa.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "thanhphohochiminh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "thuathienhue.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "tiengiang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "travinh.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "tuyenquang.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "vinhlong.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "vinhphuc.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"

[[domains]]
tld = "yenbai.vn"
registerable = "yes"
[domains.sources]
registerable = "https://vnnic.vn/sites/default/files/tailieu/vn.cctld.domains.txt"
