[[domains]]
tld = "com.ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"

[[domains]]
tld = "edu.ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"

[[domains]]
tld = "gov.ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"

[[domains]]
tld = "net.ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"

[[domains]]
tld = "org.ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"

[[domains]]
tld = "ws"
registerable = "yes"
[domains.sources]
registerable = "http://samoanic.ws/index.dhtml"
