[[domains]]
tld = "ac.zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"

[[domains]]
tld = "co.zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"

[[domains]]
tld = "gov.zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"

[[domains]]
tld = "mil.zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"

[[domains]]
tld = "org.zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"

[[domains]]
tld = "zw"
registerable = "yes"
[domains.sources]
registerable = "https://www.potraz.gov.zw/"
