[[domains]]
tld = "ак.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "обр.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "од.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "орг.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "пр.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"

[[domains]]
tld = "упр.срб"
registerable = "yes"
[domains.sources]
registerable = "https://www.rnids.rs/en/domains/national-domains"
