[[domains]]
tld = "אקדמיה.ישראל"
registerable = "yes"
[domains.sources]
registerable = "https://en.isoc.org.il/il-cctld/registration-rules"

[[domains]]
tld = "ישוב.ישראל"
registerable = "yes"
[domains.sources]
registerable = "https://en.isoc.org.il/il-cctld/registration-rules"

[[domains]]
tld = "ישראל"
registerable = "yes"
[domains.sources]
registerable = "https://en.isoc.org.il/il-cctld/registration-rules"

[[domains]]
tld = "ממשל.ישראל"
registerable = "yes"
[domains.sources]
registerable = "https://en.isoc.org.il/il-cctld/registration-rules"

[[domains]]
tld = "צהל.ישראל"
registerable = "yes"
[domains.sources]
registerable = "https://en.isoc.org.il/il-cctld/registration-rules"
